/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 crystal.gltf 
Author: Mykhailo Ohorodnichuk (https://sketchfab.com/GamePiggs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crystal-04-procedural-material-caaae60f4961491981921dd757fa00db
Title: Crystal 04 Procedural Material 💎
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/crystal.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Crystal04} rotation={[-Math.PI, 1.306, -Math.PI]} scale={1.058} />
    </group>
  )
}

useGLTF.preload('/crystal.gltf')
