/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 tree.gltf 
Author: Daniel (https://sketchfab.com/danielpetrov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-tree-2a00182b3ca4403da3f9e157184e4b42
Title: Stylized Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tree.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.big_tree_trunk_0.geometry} material={materials.trunk} />
          <mesh geometry={nodes.big_tree_leaves_0.geometry} material={materials.leaves} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.grass_grass_0.geometry} material={materials.grass} />
          <mesh geometry={nodes.grass_grass_0_1.geometry} material={materials.grass} />
        </group>
        <mesh geometry={nodes.Cylinder_green_0.geometry} material={materials.green} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree.gltf')
